src/data_test/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.flatpages import views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('repo.urls')),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('pages/', include('django.contrib.flatpages.urls')),

    path('', include('social_django.urls', namespace='social')),
    path('<path:url>', views.flatpage),
]

src/repo/urls.py
from django.contrib.flatpages import views
from django.urls import path
from .views import MainPage, GitHubLoginRedirectView

app_name = 'repo'

urlpatterns = [
    path('', MainPage.as_view(), name='main_page'),
    path('github/login/', GitHubLoginRedirectView.as_view(), name='github_login'),
    path('about-us/', views.flatpage, {'url': '/about-us/'}, name='about'),
]

src/github/models.py
from django.db import models

# Create your models here.

src/repo/models.py
from django.db import models

# Create your models here.

src/repo/forms.py
from django import forms
from django.utils.translation import gettext as _
from github.api import GitHubAPI


class CopyRepoForm(forms.Form):
    name = forms.CharField(max_length=200)
    description = forms.CharField(widget=forms.Textarea, required=False)
    homepage = forms.URLField(required=False)
    has_issues = forms.BooleanField(required=False)
    has_projects = forms.BooleanField(required=False)
    has_wiki = forms.BooleanField(required=False)

    def __init__(self, user, *args, **kwargs):
        self.github = GitHubAPI(user)
        super().__init__(*args, **kwargs)

    def clean_name(self):
        name = self.cleaned_data['name']
        if self.github.repo_exists(name):
            raise forms.ValidationError(_('Repo with current name already exists'), code='invalid')
        return name

src/repo/views.py
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, RedirectView
from django.utils.translation import gettext as _
from social_django.models import UserSocialAuth
from github.api import GitHubAPI
from .forms import CopyRepoForm


class MainPage(TemplateView):
    template_name = 'main_page.html'
    form = None
    github = None

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        try:
            self.github = GitHubAPI(request.user)
        except UserSocialAuth.DoesNotExist:
            messages.error(request, _('Please login via GitHub account'))
            return redirect('login')
        self.form = CopyRepoForm(request.user, request.POST or None, initial={
            'name': 'DataRobotTest',
            'description': 'My first self-replicated repo!',
            'homepage': 'http://localhost:8000/'
        })
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.form
        return context

    def post(self, request, *args, **kwargs):
        if self.form.is_valid():
            repo = self.github.create_repo(self.form.cleaned_data)
            skip, repo_url = repo['git_url'].split('://')
            self.github.git_push(repo_url)
            messages.success(request, _('Repo copied successfully'))
            return redirect(request.path)
        return self.get(request, *args, **kwargs)


class GitHubLoginRedirectView(RedirectView):
    url = reverse_lazy('social:begin', kwargs={'backend': 'github'})

    def get_redirect_url(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            logout(self.request)
        return super().get_redirect_url(*args, **kwargs)

src/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}DataRobot Test{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://getbootstrap.com/docs/4.1/examples/album/album.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    {% block css %} {% endblock %}
</head>
<body>
    {% include 'base/navbar.html' %}

    {% block content %} {% endblock %}

    {% block footer %}
        {% include 'base/footer.html' %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    {% block scripts %} {% endblock %}
</body>
</html>

src/templates/base/footer.html
<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>Album example is © Bootstrap, but please download and customize it for yourself!</p>
        <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting
            started guide</a>.</p>
    </div>
</footer>

src/templates/base/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="/">Main</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'repo:about' %}">About</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">{{ user.username }}</a>
                {% endif %}
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'logout' %}">Log out</a>
                    {% else %}
                        <a class="nav-link" href="{% url 'login' %}">Log In</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

src/templates/login.html
{% extends 'base/base.html' %}
{% load repo_tags %}

{% block title %}
    {{ block.super }} | Log in
{% endblock %}

{% block content %}
    <div class="container h-100 mt-5">
        {% show_messages %}
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-6">
                <h2 class="mb-5">Login</h2>
                {% if form.errors and not form.errors.username and not form.errors.password %}
                    <div class="text-danger text-center">
                        Please enter a correct username and password. Note that both fields may be case-sensitive.
                    </div>
                {% endif %}
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_username">Username</label>
                        <input type="text" class="form-control {% if form.errors.username %}is-invalid{% endif %}"
                               id="id_username" name="username" placeholder="Enter username">
                        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                        {% if form.errors.username %}
                            <div class="invalid-feedback">
                                {{ form.errors.username }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <label for="id_password">Password</label>
                        <input type="password" class="form-control {% if form.errors.password %}is-invalid{% endif %}"
                               id="id_password" name="password" placeholder="Enter password">
                        {% if form.errors.password %}
                            <div class="invalid-feedback">
                                {{ form.errors.password }}
                            </div>
                        {% endif %}
                    </div>
                    <a class="btn btn-secondary float-left" href="{% url 'repo:github_login' %}">Login with GitHub <i class="fab fa-github"></i></a>
                    <button class="btn btn-success float-right" type="submit">Login</button>
                </form>
                <br>

            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}{% endblock %}

src/templates/main_page.html
{% extends 'base/base.html' %}
{% load i18n crispy_forms_tags repo_tags %}

{% block title %}
    {{ block.super }}
{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="text-center mt-4 mb-4">{% trans 'copy repo'|capfirst %}!</h1>
        {% show_messages %}
        <form action="" method="post" id="copyRepoForm">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-success" id="copyButton">
                <span id="buttonText">{% trans 'Copy' %}</span>
                <span id="buttonLoading" style="display: none">
                    <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                    <span>Loading...</span>
                </span>
            </button>
        </form>
    </div>
{% endblock %}


{% block scripts %}
    <script>
        let form = $('#copyRepoForm');
        let button = $('#copyButton');
        let buttonText = $('#buttonText');
        let buttonLoading = $('#buttonLoading');
        form.on('submit', function(e){
            button.attr('disabled', true);
            button.attr('disabled', true);
            buttonText.hide();
            buttonLoading.show()
        })
    </script>
{% endblock %}

src/templates/repo/tags/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="text-center alert{% if message.tags %}
            alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %}
            {% endif %}">
            <button class="close" type="button" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
    {% endfor %}
{% endif %}